version: '3.8'

services:
  backend:
    image: snayderstone/back-end-causalinpact:latest
    container_name: container_backend_causalinpact
    environment:
      - GROQ_API_KEY=your-groq-api-key-here(llama 3-8b-8192)
      - OPENAI_API_KEY=your-openai-api-key-here-(gpt-3.5-turbo)
      - "5000:5000"
    networks:
      - causalinpact_net

  frontend:
    image: snayderstone/front-end-causalinpact:latest
    container_name: container_frontend_causalinpact
    ports:
      - "4173:4173"
    networks:
      - causalinpact_net

networks:
  causalinpact_net:
    driver: bridge
